[package]
name = "ogis"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
base64 = "0.22"
bytesize = "2.3.1"
clap = { version = "4.5.54", features = ["derive", "env"] }
cosmic-text = "0.15"
dotenvy = "0.15.7"
futures-util = "0.3.31"
hex = "0.4.3"
hickory-resolver = "0.25.2"
hmac = "0.12.1"
http-body-util = "0.1.3"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
infer = "0.19.0"
ip_rfc = "0.1.0"
moka = { version = "0.12", features = ["future"] }
opentelemetry = "0.31.0"
opentelemetry-otlp = { version = "0.31.0", features = ["trace", "metrics", "http-proto", "reqwest-client"] }
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio", "spec_unstable_metrics_views"] }
quick-xml = "0.38.4"
reqwest = { version = "0.12", features = ["default-tls", "stream"] }
resvg = "0.45.1"
saphyr = "0.0.6"
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10"
thiserror = "2.0.17"
tiny-skia = "0.11.4"
tokio = { version = "1.49.0", features = ["full"] }
tokio-shutdown = "0.1.5"
tower-http = { version = "0.6.7", features = ["cors"] }
tracing = "0.1.44"
tracing-opentelemetry = "0.32.0"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
url = "2.5"
usvg = "0.45.1"
utoipa = "5.4.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
webp = "0.3.1"

[dev-dependencies]
serde_json = "1.0.148"
