[package]
name = "ogis"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
resvg = "0.45.1"
serde = { version = "1.0.228", features = ["derive"] }
tiny-skia = "0.11.4"
tokio = { version = "1.48.0", features = ["full"] }
tower = "0.5.2"
usvg = "0.45.1"
