use opentelemetry::metrics::{Counter, Histogram, Meter};
use std::sync::OnceLock;

static METRICS: OnceLock<OgisMetrics> = OnceLock::new();

/// OGIS-specific metrics following OTEL semantic conventions
pub struct OgisMetrics {
    // Standard HTTP metrics
    /// Request duration in seconds
    pub request_duration: Histogram<f64>,
    /// Response body size in bytes
    pub response_size: Histogram<u64>,

    // Custom business metrics
    /// Image fetch counter (logo/image, domain, cached)
    pub image_fetch: Counter<u64>,
    /// Image size in bytes
    pub image_size: Histogram<u64>,
    /// Render duration in seconds
    pub render_duration: Histogram<f64>,
    /// Render queue wait time in seconds
    pub render_queue_wait: Histogram<f64>,
    /// Output format counter (format, scale_bucket)
    pub output_format: Counter<u64>,
}

impl OgisMetrics {
    /// Create metrics from a Meter
    pub fn new(meter: &Meter) -> Self {
        Self {
            request_duration: meter
                .f64_histogram("http.server.request.duration")
                .with_description("Duration of HTTP server requests")
                .with_unit("s")
                .build(),
            response_size: meter
                .u64_histogram("http.server.response.body.size")
                .with_description("Size of HTTP response bodies")
                .with_unit("By")
                .build(),
            image_fetch: meter
                .u64_counter("ogis.image.fetch")
                .with_description("Number of image fetch operations")
                .build(),
            image_size: meter
                .u64_histogram("ogis.image.size_bytes")
                .with_description("Size of fetched images")
                .with_unit("By")
                .build(),
            render_duration: meter
                .f64_histogram("ogis.render.duration")
                .with_description("Duration of template generation and PNG rendering")
                .with_unit("s")
                .build(),
            render_queue_wait: meter
                .f64_histogram("ogis.render.queue_wait")
                .with_description("Time waiting for render slot")
                .with_unit("s")
                .build(),
            output_format: meter
                .u64_counter("ogis.output.format")
                .with_description("Number of images generated by format")
                .build(),
        }
    }
}

/// Convert scale value to bucket for metrics (avoids high cardinality)
pub fn scale_bucket(scale: f32) -> &'static str {
    if scale >= 1.0 {
        "full"
    } else if scale >= 0.5 {
        "half"
    } else if scale >= 0.25 {
        "quarter"
    } else {
        "thumb"
    }
}

/// Initialize global metrics (called once during setup)
pub fn init_metrics(meter: &Meter) {
    let _ = METRICS.set(OgisMetrics::new(meter));
}

/// Get the global metrics instance (returns None if OTEL is disabled)
pub fn get_metrics() -> Option<&'static OgisMetrics> {
    METRICS.get()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_scale_bucket_full() {
        assert_eq!(scale_bucket(1.0), "full");
        assert_eq!(scale_bucket(1.5), "full");
        assert_eq!(scale_bucket(2.0), "full");
    }

    #[test]
    fn test_scale_bucket_half() {
        assert_eq!(scale_bucket(0.5), "half");
        assert_eq!(scale_bucket(0.75), "half");
        assert_eq!(scale_bucket(0.99), "half");
    }

    #[test]
    fn test_scale_bucket_quarter() {
        assert_eq!(scale_bucket(0.25), "quarter");
        assert_eq!(scale_bucket(0.3), "quarter");
        assert_eq!(scale_bucket(0.49), "quarter");
    }

    #[test]
    fn test_scale_bucket_thumb() {
        assert_eq!(scale_bucket(0.1), "thumb");
        assert_eq!(scale_bucket(0.2), "thumb");
        assert_eq!(scale_bucket(0.24), "thumb");
    }
}
