[project]
name = "benchmark"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.1",
    "docker>=7.1.0",
    "pillow>=12.0.0",
    "requests>=2.32.5",
]
